---
########################################################################
# pypiserver docker-compose example
########################################################################

version: "3.3"

services:
  pypiserver:
    image: pypiserver/pypiserver:latest
    volumes:
      - type: bind
        source: ./data/packages
        target: /packages
    command: -a . -P . /packages
    networks:
      - pypiserver_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./config/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./config/nginx/auth
        target: /etc/nginx/auth
      - type: bind
        source: ./data/certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot
    depends_on:
      - pypiserver
    networks:
      - pypiserver_network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  localtunnel:
    image: defunctzombie/localtunnel-server:latest
    networks:
      - pypiserver_network



networks:
  pypiserver_network:
    driver: bridge
