---
########################################################################
# pypiserver docker-compose example
########################################################################

version: "3.3"

services:
  pypiserver:
    image: pypiserver/pypiserver:latest
    volumes:
      - type: bind
        source: ./data
        target: /data
    command: -a . -P . /data/packages
    networks:
      - pypiserver_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./config/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./config/nginx/auth
        target: /etc/nginx/auth
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - pypiserver
    networks:
      - pypiserver_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


networks:
  pypiserver_network:
    driver: bridge

volumes:
  data:
