---
########################################################################
# pypiserver docker-compose example
########################################################################

version: "3.3"

services:
  pypiserver:
    image: pypiserver/pypiserver:latest
    volumes:
      - type: bind
        source: ./data
        target: /data
    command: /data/packages
    networks:
      - pypiserver_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./config/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./config/nginx/auth
        target: /etc/nginx/auth
    depends_on:
      - pypiserver
    networks:
      - pypiserver_network

networks:
  pypiserver_network:
    driver: bridge

volumes:
  data:
